# Generated by Django 4.1.5 on 2023-01-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacanciesAnalysisApp', '0002_ratiostatisticsbyarea_salarystatisticsbyarea_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratiostatisticsbyarea',
            old_name='area',
            new_name='countAreaName',
        ),
        migrations.RenameField(
            model_name='ratiostatisticsbyarea',
            old_name='ratio',
            new_name='ratioByArea',
        ),
        migrations.RenameField(
            model_name='salarystatisticsbyarea',
            old_name='avgSalary',
            new_name='avgSalaryByArea',
        ),
        migrations.RenameField(
            model_name='salarystatisticsbyarea',
            old_name='area',
            new_name='salaryAreaName',
        ),
        migrations.RenameField(
            model_name='statisticsbyyear',
            old_name='year',
            new_name='publishedYear',
        ),
    ]
